-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 11:48:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membresia` (
  `id_membresia` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_membresia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `id_membresia` INT NULL,
  `vencimiento_membresia` DATE NULL,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  PRIMARY KEY (`dni`),
  CONSTRAINT `fk_membresia`
    FOREIGN KEY ()
    REFERENCES `mydb`.`membresia` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacionamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estacionamientos` (
  `id_estacionamiento` INT NOT NULL,
  `id_ocupante` INT NULL,
  PRIMARY KEY (`id_estacionamiento`),
  UNIQUE INDEX `id_estacionamiento_UNIQUE` (`id_estacionamiento` ASC) VISIBLE,
  INDEX `fk_ocupantes_idx` (`id_ocupante` ASC) VISIBLE,
  CONSTRAINT `fk_ocupantes`
    FOREIGN KEY (`id_ocupante`)
    REFERENCES `mydb`.`usuarios` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
